### ISSUE TITLE
HTTP: 403 code when deploying

### ISSUE THREAD

**Issue by ZionMiller** [McKalvan/secpy#3]
Did anyone find a fix for this when deployed? No issues locally, but having problems with vercel.

**Comment by McKalvan** [comment]
Hi ZionMiller,

Can you please provide additional context for the exception that you are seeing? That will help narrow things down a bit more.

**Comment by ZionMiller** [comment]
Deploying a flask server on python 3.9.1 on Vercel and keep getting:

 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://data.sec.gov/api/xbrl/companyfacts/CIK0001326380.json

could it possibly be the formatting of my user agent? I'm a little unclear on the SEC documentation and the notes provided on secpy. Everything works fine locally.

Currently have ->  client = SECPyClient("<My Agent Name>")

Thanks for the quick response!

**Comment by McKalvan** [comment]
Hmm that's odd that it works locally but not elsewhere. 

I'm not familiar w/ Vercel, but I can say that setting the user-agent to an empty string will likely cause issues when making requests against the SEC REST API. 
The guidelines for user-agent values are defined here: 

https://www.sec.gov/os/webmaster-faq#developers (ctrl+f for user-agent). 

EX: 
User-Agent: | Sample Company Name AdminContact@<sample company domain>.com

I haven't had any issues just setting the user-agent to some email address, usually either my personal email or a service email for whatever app I am working on. I'd start there, but let me know if that doesn't fix things and I'll look into it some more.

**Comment by ZionMiller** [comment]
✅ doing that for the user-agent.
SECPyClient("BioBreak Research <my-email-is-here@gmail.com>")

I assume it's an issue associated with Vercel? I'm not sure why it would accept the user agent locally but not deployed. I suspect we got flagged on there or something with SEC's rate limit. WIll try other services and see if it fixes the issue. 

Thanks for all the references and help!

**Comment by ZionMiller** [comment]
Was able to deploy on python anywhere with the same files, seems to be a vercel issue incase anyone runs into a similar issue!
